all:
	g++ ~/MyProject/src/a5-ece650.c -L. -lsat -o ~/MyProject/exefiles/a5-ece650 -lpthread
	g++ ~/MyProject/src/a5-ece650_stat.c -L. -lsat -o ~/MyProject/exefiles/a5_stat -lpthread -lrt
	g++ ~/MyProject/src/a5-ece650_apr.c -L. -lsat -o ~/MyProject/exefiles/a5_apr -lpthread
	
clean:
	rm -rf *o ~/MyProject/exefiles/a5-ece650
	rm -rf *o ~/MyProject/exefiles/a5_stat
	rm -rf *o ~/MyProject/exefiles/a5_apr
	

